### ISSUE TITLE
504 while importing from Pocket

### ISSUE THREAD

**Issue by thomasschmit** [wallabag/wallabag#2027]
### Issue details

When I try to import my articles from Pocket to my Wallabag instance, I get an `504 Gateway Time-out`.

### Environment

* wallabag 2.0.3
* Installation via Docker ([`wallabag/wallabag`](https://hub.docker.com/r/wallabag/wallabag/)), using SQLite
* Pocket account with hundreds of articles

**Comment by nicosomb** [comment]
How many articles do you want to import ?

Sent from my Alcatel Onetouch Idol 3 (4.7)
Le 4 mai 2016 19:14, Thomas Schmit <notifications@github.com> a écrit :Issue details

When I try to import my articles from Pocket to my Wallabag instance, I get an 504 Gateway Time-out.

Environment


wallabag 2.0.3
Installation via Docker (wallabag/wallabag), using SQLite
Pocket account with hundreds of articles

**Comment by thomasschmit** [comment]
No idea. Probably more than one thousand!

**Comment by j0k3r** [comment]
Yeah this is mostly because it took too long to process all your articles... 😞 
We've started to work on an async integration to avoid time out like that: https://github.com/wallabag/wallabag/pull/1941

So I close this issue as duplicate.

**Comment by da-n** [comment]
Any progress on this? I am also seeing the same issue. Small server instance (EC2 Nano), so guessing it is a memory issue?

**Comment by j0k3r** [comment]
Version 2.1 will include the async way to import content. It'll we released this month.

**Comment by da-n** [comment]
Ok awesome, thanks. I am moving from Instapaper. Which meant opening up an Pocket account, importing, then creating an app to get API key, so to have the import fail is a real blow. But I'm looking forward to trying it out. Hoping I can contribute once on board as well. Thanks.

**Comment by j0k3r** [comment]
Oh if you aren't in a rush, we plan to implement Instapaper import as well, but not in the first release of 2.1.0, but on a minor one :)

**Comment by da-n** [comment]
Just to follow up, I updated to latest version today and despite seeing a timeout the articles all got pulled down correctly, so problem has been resolved. Thanks for the awesome project!

**Comment by McMac** [comment]
Still having this issue with 2.1.3 docker version of wallabag. :(

**Comment by tcitworld** [comment]
I guess Redis can be enabled on the docker images for asynchronous import ?

**Comment by McMac** [comment]
Thanks! Looking at the changes I found out that it can be enable. Didn't see them documented - or just looked at the wrong place.

**Comment by egeogretmen** [comment]
I'm using a shared hosting (yea, I know...) and it gives a timeout after importing from pocket, fetching only 20 of the articles out of maybe 50-60. If I hit import again, I get some of the articles as duplicate, while some not. Any ideas how to solve this efficiently? Pocket gives an [html export](https://getpocket.com/export), so that might come in handy in cases like this.

**Comment by McMac** [comment]
I tried Redis, without Redis, with Mysql, with SQLite, with Docker, without Docker. It just keeps dying either before (504) or somewhere in between where you then can't recover but only get duplicates. 
If it only were Java then I could at least help fix it. :-S

**Comment by ryanpcmcquen** [comment]
Still having 504s with import (I am on `framabag`). Is there another fix incoming?

**Comment by tcitworld** [comment]
The terms of Framabag say that async export (which is the fix for this) is not enabled because Framabag is only intended as a demo version to discover the service, limited to 1000 articles per account. Therefore allowing to import hundreds and hundreds of articles makes no sense for this service.
If you have a reasonable number of articles (from another source than Pocket) but fail to import them, contact Framasoft at https://contact.framasoft.org/ and we will do it manually. Otherwise, we really advise you to have a look at https://wallabag.it/
