### ISSUE TITLE
wallabag can't retrieve contents for this article: theatlantic.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2075]
### Issue details

http://www.theatlantic.com/international/archive/2013/10/behind-the-bad-indian-coder/280636/
http://www.theatlantic.com/technology/archive/2013/06/fix-things-never-force-it-lessons-from-grandpa/276873/

Content is not loaded.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by Strubbl** [comment]
a workaround is to add the page www.theatlantic.com/amp/article/276873/

@j0k3r can this be automated since the url is always the same except the article ID in the end?

**Comment by Strubbl** [comment]
Yes!!! single_page_link is the solution.

**Comment by Strubbl** [comment]
should be fixed with https://github.com/j0k3r/graby-site-config/pull/11

**Comment by j0k3r** [comment]
I closed your PR on my fork because it's better to submit PR about siteconfig to the original repo (https://github.com/fivefilters/ftr-site-config) :)

**Comment by chepec** [comment]
This is still an issue for some articles from theatlantic.com (though not all, not sure what differs).

This fails:
`http://www.theatlantic.com/entertainment/archive/2015/06/clear-the-kitchen-table-how-apple-and-ibm-marketed-the-first-personal-computers/396047/ `

Whereas this manual fix (as per suggestion above) works:
`http://www.theatlantic.com/entertainment/amp/article/396047/`

Installed via `git clone`, 2.0.5, PHP 5.6.22, Debian Jessie 8.5, dedicated VPS, MySQL.

**Comment by j0k3r** [comment]
@chepec this will be fixed in the next wallabag release (see https://github.com/fivefilters/ftr-site-config/pull/171).
Feel free to put a comment here if it's not the case.
