### ISSUE TITLE
Wrong display in wallabag (bloomberg.com)

### ISSUE THREAD

**Issue by dariottolo** [wallabag/wallabag#3697]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

If I try to add to Wallabag an article fom blloberg.com (for example https://www.bloomberg.com/news/features/2018-07-18/japan-s-lonely-death-industry ) the result in wallabeg is an entry with the title "Terms of Service Violation" and as content:

> Your usage has been flagged as a violation of our terms of service.
> 
> For inquiries related to this message please contact support. For sales inquiries, please visit http://www.bloomberg.com/professional/request-demo
> 
> If you believe this to be in error, please confirm below that you are not a robot by clicking "I'm not a robot" below.
> 
> Please make sure your browser supports JavaScript and cookies and that you are not blocking them from loading. For more information you can review the Terms of Service and Cookie Policy.
> 
> Block reference ID:

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? via cpanel softaculous
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.1
* OS:
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):  10.0.34-MariaDB-cll-lve

### Steps to reproduce/test case

Just open Wallabag, click on the + to add an article and enter
https://www.bloomberg.com/news/features/2018-07-18/japan-s-lonely-death-industry

P.S.: http://f43.me/feed/test and http://siteconfig.fivefilters.org/ can not fetch the content of the original article.

**Comment by 4oo4** [comment]
I ran into this too, I'm not sure how they detect this but it seems to be something that goes beyond IP address/user-agent. For now, you can normally find the exact same articles on bloombergquint.com, they don't appear to have that kind of detection.

**Comment by anarcat** [comment]
another instance: https://www.bloomberg.com/news/features/2018-10-04/the-big-hack-how-china-used-a-tiny-chip-to-infiltrate-america-s-top-companies

archive.org and archive.is also both fail to archive the contents.

**Comment by biva** [comment]
Thanks for the tip with bloombergquint.com. Would it be possible to use an intelligent http redirect in `/var/www/html/wallabag/vendor/j0k3r/graby/src/Extractor/HttpClient.php`?

I tried:
<code>'bloomberg.com/news/articles/2018-10-16' => ['bloombergquint.com/business'],</code>
but it doesn't work. And above all, the redirection should work for any date (not only `2018-10-16`)

Any idea?

**Comment by techexo** [comment]
@biva: Actually you were very close! The following redirection should work: 
`'www.bloomberg.com' => ['www.bloombergquint.com'],`
 as _bloombergquint_ seem to have implemented a redirection from `www.bloombergquint.com/articles/XXXX-XX-XX/a-bloomberg-article` to `www.bloombergquint.com/a-bloomberg-article` to match the URL patterns of `bloomberg.com`.

**Comment by techexo** [comment]
@biva Could you confirm this workaround work in order to close the issue? :)

**Comment by biva** [comment]
@techexo Thank you! Just for the record, the full line to add in `/var/www/html/wallabag/vendor/j0k3r/graby/src/Extractor/HttpClient.php` is:
`'www.bloomberg.com' => ['www.bloomberg.com' => 'www.bloombergquint.com'],`

**Comment by techexo** [comment]
Oups, I forgot a part of it! Sorry 🙏

**Comment by biva** [comment]
I did not open this issue, so I can't close it :)

**Comment by anarcat** [comment]
sorry, this was fixed in wallabag? i'm not sure i followed how...

**Comment by j0k3r** [comment]
Yeah sorry I closed too fast.
The issue isn't fixed but @techexo & @biva found a way to fix it.

**Comment by techexo** [comment]
@j0k3r I am not sure how it could be fixed, as it seems that you have to both support JavaScript and cookies management to access bloomberg's website.
When trying to fetch from wallabag, the `url` field is one redirecting to _Bloomberg - Are you a robot?_ webpage, that specify

> Why did this happen?
> Please make sure your browser supports JavaScript and cookies and that you are not blocking them from loading. 

Could graby HttpClient be updated in such a way? If not, we should probably make permanent this redirection (cf https://github.com/wallabag/wallabag/issues/3792).

**Comment by Kdecherf** [comment]
I think we should give a try to headless browsers to handle dynamic rendering like this.

**Comment by anarcat** [comment]
On 2018-11-30 02:08:58, Kevin Decherf wrote:
> I think we should give a try to headless browsers to handle dynamic rendering like this.

That.

More broadly, I think wallabag should be more careful about the raw
content it fetches when it crawls articles. It should use WARC files as
they allow keeping all resources in a single file, including HTTP
headers, for a more faithful playback. Using a headless browser would
also allow PDF and PNG snapshots to be taken that reflect exactly the
page content.

This would make Wallabag double as a webpage archival system, which I
would find very, very useful in my workflow. As things stand now, i have
8000 links in Wallabag, but statistically, over 90% of those are dead
links now and Wallabag can't really help in restoring that content, as
the saved data is the "filtered" version, which often fails on sites
like this... Having the original copy available would allow Wallabag to
re-render the site even if the original content is gone, so that we
could retroactively fix those issues correctly. :)

**Comment by anarcat** [comment]
Alternatively, it might be useful if wallabag apps would directly feed the DOM content from the browser into wallabag, that way the server wouldn't have to run a headless browser and we'd just reuse the one on the client side. The API is already there on the server side, but client support is lacking (e.g. https://github.com/wallabag/wallabagger/issues/105).

**Comment by anarcat** [comment]
should i bring this up in the design discussion instead?

**Comment by techexo** [comment]
@anarcat In my humble opinion, yes, at least to explain your use of wallabag, not for the technical part.

**Comment by Kdecherf** [comment]
Hello there,

It seems that Bloomberg does not block wallabag from fetching content anymore. The last remaining issue is the handling of json-ld, which is global and addressed by a separated issue.

**Comment by Kdecherf** [comment]
Therefore I think this issue can be closed.

**Comment by dariottolo** [comment]
It does not work for me on WB 2.3.6.
I just tried adding https://www.bloomberg.com/news/articles/2019-02-06/nissan-blow-leads-to-regret-and-defiance-in-a-brexit-heartland?srnd=premium-europe
WB saves the article with title "Bloomberg - Are you a robot?" and content "wallabag can't retrieve contents for this article. Please troubleshoot this issue."

**Comment by Kdecherf** [comment]
@dariottolo where is hosted your instance?

**Comment by dariottolo** [comment]
Selfhosted on my own domain.

**Comment by Kdecherf** [comment]
Which provider?

**Comment by dariottolo** [comment]
https://www.hawkhost.com/shared-web-hosting

I think I installed it initially via Softacolous then updated using instructions for shared hosting.
It might that only core files have been updated though.

**Comment by 4oo4** [comment]
I can confirm that I'm also not able to save articles, like @dariottolo . I think once it thinks you're a robot, your IP (and maybe also your user agent?) are blacklisted until you do the captcha. @dariottolo , if you try what I mention here then you might be able to get them to save again, I'm going to try that in a bit and see too.

https://github.com/wallabag/wallabag/issues/3697#issuecomment-408687225

Unfortunately, I think the more articles you try to save from them to Wallabag, the more likely they are to blacklist you until yo do the captcha.

**Comment by dariottolo** [comment]
I can not connect to the website and solve the captcha from the server where WB is installed.
I do not know if they blacklisted the IP or it depends on the user agent.

**Comment by syclops** [comment]
I don't know if this is a universal thing, but Bloomberg Quint now seems to only show the first few sentences of the article and then directs the reader to the main Bloomberg site. Accordingly, the trick of rewriting `bloomberg.com` to `bloombergquint.com` no longer works. Are others also finding this to be the case, and if so, is there another workaround?

**Comment by techexo** [comment]
@syclops It seems that Bloomberg Quint has "upgraded" their website and don't use bloomberg's full-text anymore... Unfortunately, I don't see an immediate hack to go around this change, sorry...

**Comment by 4oo4** [comment]
I wonder if they are reading this thread and thwarting us accordingly? :laughing:

**Comment by maltokyo** [comment]
Still have this issue, but quint trick seems to work again now in 2021, anyone else?

**Comment by hrehfeld** [comment]
I'm also getting `wallabag can't retrieve contents for this article. Please troubleshoot this issue.` on https://www.bloomberg.com/opinion/articles/2021-02-19/gamestop-hearing-featured-no-cats

**Comment by Kdecherf** [comment]
A workaround is available through wallabagger, see https://github.com/wallabag/wallabagger/releases/tag/v1.14.0

I'm closing this issue

**Comment by anarcat** [comment]
that doesn't work from the android app though, nor from anything else than wallabagger...

**Comment by 97-109-107** [comment]
`http://archive.today/` is capable of getting the source, but wallabag can't access archive.today due to captcha. 

I'm trying to think of a route between _news outlet_ -> _archive.today_ -> _intermediate format or mirror_ -> _wallabag_

**Comment by 4oo4** [comment]
@97-109-107 There is the mementoweb API that they support, but that also requires a captcha:

http://mementoweb.org/depot/native/archiveis/

That would allow you to grab an article like this:

`https://archive.is/timegate/http://www.w3.org/TR/webarch/`
