### ISSUE TITLE
500 Internal Server Error on js/routing?callback=fos.Router.setData

### ISSUE THREAD

**Issue by thansk** [wallabag/wallabag#4850]
deleted

**Comment by thansk** [comment]
Any help?

**Comment by LucTech** [comment]
Hi,
Having the same error 500 on js/routing?callback=fos.Router.setData from login. And cannot connect.
But sadly no solution.

In my case it's a new wallabag instance. With docker.
User exists in database.

It seems to be a session problem.
There are those message in log just before error 500 : 
```
wallabag-wallabag   | 2020/12/30 20:57:07 [error] 187#187: *38 FastCGI sent in stderr: "PHP message: PHP Warning:  SessionHandler::read(): open(/var/www/wallabag/var/sessions/prod/sess_9410fd618052e26caaf72c716ce07563, O_RDWR) failed: Permission denied (13) in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php on line 48PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/wallabag/vendor/friendsofsymfony/jsrouting-bundle/Extractor/ExposedRoutesExtractor.php on line 174" while reading response header from upstream, client: 172.22.0.4, server: _, request: "GET /js/routing?callback=fos.Router.setData HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.servsumo.fr", referrer: "https://wallabag.servsumo.fr/login"
wallabag-wallabag   | 172.22.0.4 - - [30/Dec/2020:20:57:07 +0000] "GET /js/routing?callback=fos.Router.setData HTTP/1.1" 500 69 "https://wallabag.servsumo.fr/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
```
Rights seem ok (root owner!) : 
```
docker exec -t wallabag-wallabag ls -l /var/www/wallabag/var/sessions/prod
total 8
-rw-------    1 root     root           119 Dec 30 20:35 sess_37e5467b4dae4c0110ff7e3e0847794f
-rw-------    1 root     root           119 Dec 30 20:36 sess_3b4c4a1e4ef21bbf1d6be666ea23f694
docker exec -t wallabag-wallabag id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```

Maybe have anyone meet this error before us ?

Luc

**Comment by LucTech** [comment]
It's (temporarly) ok when I change rights on cache directories : jms_serializer and hateoas
chmod a+w /var/www/wallabag/var/cache/prod/jms_serializer
chmod a+w /var/www/wallabag/var/cache/prod/hateoas/

But it's ... KO again, as I clear cache : /var/www/wallabag/bin/console cache:clear --env=prod --no-interaction
Luc

**Comment by LucTech** [comment]
re-hi,
In fact, all my problems are solved since I **use "latest"** instead of "2.4.0" docker image.
No more Error 500 because of directories rights.
Androïd synchronisation ok...
great thanks to developpers and image maintenairs !!!!

**Comment by thansk** [comment]
I updated to the last version and it still wasn't fixed so I reinstalled it this time choosing to drop the database and everything and it finally worked.

**Comment by podiki** [comment]
Similar error here, resolved by setting permissions as stated in the documentation. I didn't catch it at first since it was only certain subfolders that had the wrong permissions, probably from running `sudo php` and then not setting permissions for created files?

```
FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /usr/share/webapps/wallabag/vendor/friendsofsymfony/jsrouting-bundle/Extractor/ExposedRoutesExtractor.php on line 174" while reading response header from upstream, request: "GET /wallabag/js/routing?callback=fos.Router.setData HTTP/2.0
```

**Comment by thelazyoxymoron** [comment]
I was facing similar issue, resolved it by setting the appropriate permissions on the entire `wallabag` directory:
```
docker exec -t wallabag-app chown -R nobody:nobody /var/www/wallabag
```

**Comment by nicosomb** [comment]
As the first post is deleted, I close this issue. 
If someone has an issue like this one, please open a new one.
