### ISSUE TITLE
generated epub with wrong metadata

### ISSUE THREAD

**Issue by Monirzadeh** [wallabag/wallabag#5596]
### Environment

* **Version**: 2.4.2
* **Installation**: docker image
* **PHP version**:
* **OS**: Debian
* **Database**: MariaDB

</details>

### What steps will reproduce the bug?
create a epub version of some persian webpage [example](https://www.1pezeshk.com/archives/2022/01/the-machinist-2004.html) than check epub metadata.
if you see source code of saved article in wallabag webapp you see `lang="fa-IR"` that mean wallabag detect language correctly but when it make epub set language metadata uncorrected to english.

### why is it important?
some app reader automatically read metadata and base on that implement some style for specific language.

**Comment by j0k3r** [comment]
Thanks for the report @Monirzadeh!
We defined the language from the entry without checking it. `fa-IR` isn't accepted by epub, we must use `fa` instead. I've fixed it in a PR #5647

**Comment by Monirzadeh** [comment]
i try to test that (have some wired problem with setup development environment) if i can successfully build that report any problem here.
about [this](https://github.com/wallabag/wallabag/pull/5647#issuecomment-1057365878). my first target for this feature is [koreader](https://github.com/koreader/koreader). i try to test that on this for now.
thanks for your followup
P.S. is it possible for you to add more details to how setup development environment in wallabag wiki it can be helpful.

**Comment by Monirzadeh** [comment]
hi @j0k3r sorry for late response i check this commit and it better than before but some wired behavior observe.
i test that with multiple link but some problem still exist.
we get different tag for same language.
for example
[this article](https://www.1pezeshk.com/archives/2022/02/why-your-brain-is-a-time-machine-living-15-seconds-in-the-past.html)  languge tag is `fa-IR`
but [this one](https://fa.wikipedia.org/wiki/%D9%BE%D8%B3%D8%AA%DA%AF%D8%B1%D8%B3%E2%80%8C%DA%A9%DB%8C%D9%88%D8%A7%D9%84) languge tag is `fa`

another that maybe not related. [this](https://blog.alihoseiny.ir/%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA%D8%8C-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A2%D8%B2%D8%A7%D8%AF%DB%8C/) page language tag detect as `en` instead of `fa-IR`
