### ISSUE TITLE
Display better title than "Untitled"

### ISSUE THREAD

**Issue by mochtu** [wallabag/wallabag#564]
When wallabag is unable to retrieve full text content of a saved link, the automatically chosen title for the item is "Untitled".

A much better solution would be to use the raw link as the item's title, imho. Maybe together with a [Error fetching item] at the end of the title.

Cheers,
Moritz

Wallabag Version 1.5.3

**Comment by tcitworld** [comment]
Fixed both on v2 and v1.9.x

**Comment by mkollaro** [comment]
I'm still experiencing this on 1.9.1 when I try to save a link that it cannot put into a nice readable format, e.g. discussions on https://news.ycombinator.com. It should try to set the title correctly, or at least set the url as the title.

**Comment by tcitworld** [comment]
Sorry, I should have said v1.9.2.

**Comment by j0k3r** [comment]
It's fixed in v2.
